/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DayCheckbox: typeof import('./components/DayCheckbox.vue')['default']
    DayItem: typeof import('./components/DayItem.vue')['default']
    MonthItem: typeof import('./components/MonthItem.vue')['default']
    MyCalendar: typeof import('./components/MyCalendar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
